export enum ERROR_CODE {

    // AUTHORIZATION_ERROR
    AUTHORIZATION_ERROR = "AUTH0001",
    MISSING_CREDENTIALS = "AUTH0002",
    INVALID_CREDENTIALS = "AUTH0003",

    // VALIDATION
    // USER
    INVALID_USER_EMAIL = "VAL0001",
    INVALID_USER_PASSWORD = "VAL0002",
    MISSING_USER_EMAIL = "VAL0003",
    MMISSING_USER_PASSWORD = "VAL0004",
    MISSING_USER_NAME = "VAL0005",

    // UNKNOWN
    UNKNOWN_SERVER_ERROR = "UKN0000",
}
