export enum ERROR_CODE {

    // AUTHORIZATION_ERROR
    AUTHORIZATION_ERROR = "AUTH0101",
    MISSING_CREDENTIALS = "AUTH0102",
    INVALID_CREDENTIALS = "AUTH0103",

    // VALIDATION
    INVALID_FIELDS = "VAL0101",

    // UNKNOWN
    UNKNOWN_SERVER_ERROR = "UKN0000",
}